#!/usr/bin/env ruby


load "#{ File.dirname( __FILE__ ) }/lib/lucie/version.rb"


def disable
  load './script/disable_node'
end


def add
  load './script/add_node'
end


def remove
  load './script/remove_node'
end


def enable
  load './script/enable_node'
end


def install
  load './script/install_node'
end


def list
  load './script/list_node'
end


def version
  puts <<-EOL
Lucie, version #{ Lucie::VERSION::STRING }
Copyright (C) 2007 Yasuhito TAKAMIYA
  EOL
end


def help
  command = ARGV.shift

  ARGV.clear << '--help'
  if command.nil?
    puts <<-EOL
Usage: node <command> [options] [args]

Lucie node command-line tool, version #{ Lucie::VERSION::STRING }
Type 'node help <command>' for help on a specific command.
Type 'node --version' to see the version number.

Available commands:
  add        - adds a node
  remove     - removes a node
  enable     - enable installation of a node
  disable    - disable installation of a node
  list       - list registered nodes

Lucie is an Automatic Cluster Installer.
For additional information, see http://lucie.is.titech.ac.jp/
    EOL
  elsif method_for_command( command )
    self.send( method_for_command( command ) )
  else
    STDERR.puts "Type 'node help' for usage."
    exit -1
  end
end


def method_for_command command
  case command
  when 'disable'
    return :disable
  when 'add'
    return :add
  when 'delete', 'remove', 'rm', 'del'
    return :remove
  when 'enable'
    return :enable
  when 'install'
    return :install
  when 'list'
    return :list
  when 'version', '-v', '--version'
    return :version
  when 'help', '-h', '--help', '/?', '-?'
    return :help
  else
    return nil
  end
end


command = ARGV.shift
if method_for_command( command )
  require 'fileutils'
  FileUtils.cd( File.dirname( __FILE__ ) ) do
    self.send method_for_command( command )
  end
elsif command.nil?
  STDERR.puts "Type 'node --help' for usage."
  exit -1
else
  STDERR.puts "Unknown command : '#{ command }'"
  STDERR.puts "Type 'node --help' for usage."
  exit -1
end


### Local variables:
### mode: Ruby
### coding: utf-8
### indent-tabs-mode: nil
### End:
