#!/usr/bin/env ruby
#
# $Id$
#
# Author:: Yasuhito Takamiya (mailto:yasuhito@gmail.com)
# Revision:: $LastChangedRevision$
# License:: GPL2


load "#{ File.dirname( __FILE__ ) }/lib/lucie/version.rb"


def add
  load File.dirname( __FILE__ ) + "/script/add_node"
end


def install
  load File.dirname( __FILE__ ) + "/script/install_node"
end


def version
  puts <<-EOL
Lucie, version #{ Lucie::VERSION::STRING }
Copyright (C) 2007 Yasuhito TAKAMIYA
  EOL
end


def help
  command = ARGV.shift
  
  ARGV.clear << '--help'
  if command.nil?
    puts <<-EOL
Usage: node <command> [options] [args]

Lucie node command-line tool, version #{ Lucie::VERSION::STRING }
Type 'node help <command>' for help on a specific command.
Type 'node --version' to see the version number.

Available commands:
  add        - adds a node

Lucie is a Automatic Cluster Installer.
For additional information, see http://lucie.is.titech.ac.jp/trac/lucie/
    EOL
  elsif method_for_command( command )
    self.send( method_for_command( command ) )
  else
    STDERR.puts "Type 'node help' for usage."
    exit -1
  end
end


def method_for_command command
  case command
  when 'add'
    return :add
  when 'install'
    return :install
  when 'version', '-v', '--version'
    return :version
  when 'help', '-h', '--help', '/?', '-?'
    return :help
  else 
    return nil
  end
end


command = ARGV.shift
if method_for_command( command )
  self.send method_for_command( command )
elsif command.nil?
  STDERR.puts "Type 'node --help' for usage."
  exit -1
else
  STDERR.puts "Unknown command : '#{ command }'"
  STDERR.puts "Type 'node --help' for usage."
  exit -1
end


### Local variables:
### mode: Ruby
### coding: utf-8
### indent-tabs-mode: nil
### End:
