#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../../lib/" ) )


require "command/node-history"
require "configuration"
require "lucie/log"
require "lucie/script"


Lucie::Log.path = File.join( Configuration.log_directory, "node-history.log" )


def target_node
  ARGV.each do | each |
    return each unless /\A\-/=~ each
  end
end


begin
  app = Command::NodeHistory::App.new
  app.usage_and_exit if target_node.empty?
  app.main target_node
rescue => e
  Lucie::Script.handle_exception e, app
  exit -1
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:

