#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../../lib/" ) )


require "blocker"
require "command/node-install-multi"
require "lucie/script"


Blocker.start do
  begin
    app = Command::NodeInstallMulti::App.new
    app.main
  rescue => exception
    Lucie::Script.handle_exception exception, app
    exit -1
  end
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
