#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../../lib/" ) )


require "blocker"
require "command/node-install-multi"
require "lucie/script"


def node_options
  Command::NodeInstallMulti::Parser.new( ARGV ).parse
end


begin
  Blocker.block
  app = Command::NodeInstallMulti::App.new
  app.usage_and_exit if node_options.empty?
  app.main node_options
rescue => exception
  Lucie::Script.handle_exception exception, app
  exit -1
ensure
  Blocker.release
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
