#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../../lib/" ) )


require "blocker"
require "command/node-install"
require "lucie/script"


def target_node
  ARGV.each do | each |
    next if /\A\-/=~ each
    return each
  end
end


Blocker.start do
  begin
    app = Command::NodeInstall::App.new
    app.usage_and_exit if target_node.nil?
    app.main target_node
  rescue => e
    Lucie::Script.handle_exception e, app
    exit -1
  end
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
