#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../../lib/" ) )


require "blocker"
require "command/node-install-multi"
require "lucie/script"


def target_nodes
  nodes = {}
  ARGV.each do | each |
    next if /\A\-/=~ each
    next if /\A\S+\Z/=~ each
    options = each.split( /\s+/ )
    nodes[ options.first ] = options[ 1..-1 ]
  end
  nodes
end


begin
  Blocker.block
  app = Command::NodeInstallMulti::App.new
  app.usage_and_exit if target_nodes.empty?
  app.main target_nodes
rescue => e
  Lucie::Script.handle_exception e, app
  exit -1
ensure
  Blocker.release
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
