#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../../lib/" ) )


require "blocker"
require "command/node-reset"
require "configuration"
require "lucie/log"
require "lucie/script"


Lucie::Log.path = File.join( Configuration.log_directory, "node-reset.log" )


begin
  Blocker.block
  app = Command::NodeReset::App.new
  app.main
rescue => e
  Lucie::Script.handle_exception e, app ? app.options.verbose : nil
  exit -1
ensure
  Blocker.release
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
