#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../../lib/" ) )


require "blocker"
require "lucie/script"
require "command/node-update"


Lucie::Log.path = File.join( Configuration.log_directory, "node-update.log" )


def target_nodes
  nodes= []
  ARGV.each do | each |
    break if /\A\-/=~ each
    nodes << each
  end
  nodes
end


Blocker.start do
  begin
    app = Command::NodeUpdate::App.new
    app.usage_and_exit if target_nodes.empty?
    app.main target_nodes
  rescue => e
    Lucie::Script.handle_exception e, app
    exit -1
  end
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
