#!/usr/bin/env ruby
#
# $Id$
#
# Author:: Yasuhito Takamiya (mailto:yasuhito@gmail.com)
# Revision:: $LastChangedRevision$
# License:: GPL2


# ENV[ 'RAILS_ENV' ] = 'production'


require File.dirname( __FILE__ ) + '/../config/boot'
require 'optparse'


node_name = ARGV.shift
mac_address = nil
trace = false


ARGV.options do |opts|
  opts.banner = 'usage: node add <node-name> --mac <MAC address>'

  opts.separator ''
  opts.on( '-m', '--mac MAC address', String,
           "The MAC address of the NIC (eg. 00:E0:81:05:D3:8B)" ) do | v|
    mac_address = v
  end

  opts.on( '-t', '--trace', 'Print out exception stack traces' ) do
    trace = true
  end

  opts.separator ''

  opts.on( '-h', '--help', 'Show this help message.' ) do
    puts opts
    exit 1
  end

  args = opts.parse!

  unless node_name and mac_address
    STDERR.puts 'Node name and Mac address are mandatory'
    STDERR.puts
    puts opts
    exit -1
  end

  # Node Name can only contain alphanumeric characters and numbers
  if node_name.match /[^-_a-zA-Z0-9]/
    STDERR.puts "'#{node_name}' is not a valid node name. Node name should only contain alphanumeric characters and numbers, dashes and underscores, and no whitespace."
    exit -1
  end

  hex = /[a-fA-F0-9][a-fA-F0-9]/
  unless mac_address.match /\A#{hex}:#{hex}:#{hex}:#{hex}:#{hex}:#{hex}\Z/
    STDERR.puts "'#{mac_address}' is not a valid MAC address."
    exit -1
  end
end


puts "Adding node '#{node_name}' (this may take a while)..."

begin 
  require RAILS_ROOT + '/config/environment'

  node = Node.new( node_name, mac_address )
  nodes = Nodes.load_all
  nodes << node

rescue => e
  if trace
    raise
  else
    STDERR.puts "FAILED: #{e.message}"
    exit -1
  end
end


puts "Node '#{node_name}' added."


### Local variables:
### mode: Ruby
### coding: utf-8
### indent-tabs-mode: nil
### End:
