#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../lib/" ) )


require "blocker"
require "command/confidential-data-server"
require "lucie/script"


Blocker.start "confidential-data-server" do
  begin
    app = Command::ConfidentialDataServer::App.new
    app.main
  rescue Interrupt
    $stderr.puts "Interrupted"
    exit 0
  rescue => exception
    Lucie::Script.handle_exception exception, app
    exit -1
  end
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
