#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../lib/" ) )


require "command/confidential-data-server"
require "lucie/script"


begin
  app = Command::ConfidentialDataServer::App.new
  app.main
rescue Interrupt
  $stderr.puts "Interrupted"
  exit 0
rescue => e
  Lucie::Script.handle_exception e, app
  exit -1
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
