#!/usr/bin/env ruby


ENV[ 'RAILS_ENV' ] = 'production'

LUCIE_THIS_PROCESS_IS_BUILDER = true

require File.dirname( __FILE__ ) + '/../config/boot'
require 'optparse'


node_name = ARGV.shift
trace = false


ARGV.options do |opts|
  opts.banner = 'usage: node disable <node-name>'

  opts.separator ''

  opts.on( '-t', '--trace', 'Print out exception stack traces' ) do
    trace = true
  end

  opts.separator ''

  opts.on( '-h', '--help', 'Show this help message.' ) do
    puts opts
    exit 1
  end

  args = opts.parse!

  if node_name == '--help' or node_name == '-h'
    puts opts
    exit 1
  end
end


begin
  require RAILS_ROOT + '/config/environment'
  require 'drb/drb'

  lucie_daemon = LucieDaemon.server
  lucie_daemon.disable_node( node_name )

rescue DRb::DRbConnError
  if trace
    raise
  else
    STDERR.puts "FAILED: Lucie daemon (lucied) is down."
    exit -1
  end
rescue => e
  if trace
    raise
  else
    STDERR.puts "FAILED: #{ e.message }"
    exit -1
  end
end


### Local variables:
### mode: Ruby
### coding: utf-8
### indent-tabs-mode: nil
### End:
