#!/usr/bin/env ruby


RAILS_ENV = 'install_multi'


require File.join( File.dirname( __FILE__ ), '..', 'config', 'environment' )
require 'fileutils'
require 'optparse'
require 'popen3/shell'


trace = false


opts = OptionParser.new

opts.banner = 'usage: install_multi <node-name>, <node-name>, ...'

opts.separator ''

opts.on( '-v', '--verbose', 'Be verbose.' ) do
  Lucie::Log.verbose = true
end

opts.on( '-t', '--trace', 'Print out exception stack traces' ) do
  Lucie::Log.verbose = true
  trace = true
end

opts.on( '-h', '--help', 'Show this help message.' ) do
  puts opts
  exit 1
end

opts.parse! ARGV


begin
  trace_option = trace ? '--trace' : ''
  nodes = ARGV.shift.split( ',' )

  Array.new( nodes.size ) do | i |
    Thread.new( i ) do | j |
      Thread.stop
      FileUtils.cd( File.dirname( __FILE__ ) ) do
        system "../node install #{ nodes[ j ] } #{ trace_option }"
      end
    end
  end.each do | t |
    t.wakeup
  end

rescue Interrupt
  Lucie::Log.error 'Interrupted.'
  exit -1
rescue MandatoryOptionError => e
  Lucie::Log.error e.message
  STDERR.puts
  STDERR.puts opts
  exit -1
rescue => e
  Lucie::Log.error e.message
  if trace
    e.backtrace.each do | each |
      Lucie::Log.error each
    end
  end
  exit -1
end


while Thread.list.size > 1
  sleep 1
end

Lucie::Log.verbose = true
Lucie::Log.info "Node #{ nodes.join( ',' ) } installed."


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
