#!/usr/bin/env ruby


require 'English'
require 'install-packages/app'
require 'install-packages/options'


if __FILE__ == $PROGRAM_NAME
  options = InstallPackages::Options.new.parse( ARGV )
  InstallPackages::App.instance.main options
end


### Local variables:
### mode: Ruby
### indent-tabs-mode: nil
### End:
