#!/usr/bin/env ruby


ENV[ 'RAILS_ENV' ] = 'production'

LUCIE_THIS_PROCESS_IS_BUILDER = true


require File.dirname( __FILE__ ) + '/../config/boot'
require 'optparse'


node_name = ARGV.shift
mac_address = nil
trace = false


ARGV.options do |opts|
  opts.banner = 'usage: node list'

  opts.separator ''

  opts.on( '-t', '--trace', 'Print out exception stack traces' ) do
    trace = true
  end

  opts.separator ''

  opts.on( '-h', '--help', 'Show this help message.' ) do
    puts opts
    exit 1
  end

  args = opts.parse!

  if node_name == '--help' or node_name == '-h'
    puts opts
    exit 1
  end
end


begin
  require RAILS_ROOT + '/config/environment'

  nodes = Nodes.load_all

  puts "Nodes directory = '#{ nodes.dir }'"
  if nodes.size == 0
    puts 'No node is added yet.'
  else
    nodes.list.each do | each |
      if each.latest_install and each.latest_install.incomplete?
        printf "incomplete %s (installer = %s)\n", each.name, each.installer_name
      elsif each.latest_install and each.latest_install.failed?
        printf "      fail %s (installer = %s)\n", each.name, each.installer_name
      elsif each.enable?
        printf "     ready %s (installer = %s)\n", each.name, each.installer_name
      elsif each.latest_install
        printf "%10s %s (installer = %s)\n", each.latest_install.status, each.name, each.installer_name
      else
        printf "           %s (installer = %s)\n", each.name, each.installer_name
      end
    end
  end
rescue => e
  if trace
    raise
  else
    STDERR.puts "FAILED: #{ e.message }"
    exit -1
  end
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
