#!/usr/bin/env ruby


ENV[ 'RAILS_ENV' ] = 'lucied'


require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'


LucieDaemon.daemonize


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
