#!/usr/bin/env ruby


$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) + "/../lib/" ) )


require "command/secret-server"


begin
  app = Command::SecretServer::App.new
  app.main
rescue Interrupt
  $stderr.puts "Interrupted"
  exit 0
rescue => e
  $stderr.puts "ERROR: " + e.message
  if app and app.options.verbose
    e.backtrace.each do | each |
      $stderr.puts each
    end
  end
  exit -1
end


### Local variables:
### mode: Ruby
### coding: utf-8-unix
### indent-tabs-mode: nil
### End:
