#!/usr/bin/env ruby


File.open( '/etc/shadow', 'r' ) do | f |
  f.each do | l |
    if /^(root:[^:]+)/=~ l
      system %{echo "#{ $1 }" | chroot /tmp/target chpasswd --encrypted}
      system "chroot /tmp/target shadowconfig on"
      exit
    end
  end
end


