#!/usr/bin/env ruby


require 'facter'


$host_name = ARGV[ 0 ]
$mac_address = ARGV[ 1 ].downcase
$domain_name = ARGV[ 2 ]
$lucie_server = ARGV[ 3 ]
$lucie_server_ipaddress = ARGV[ 4 ]


File.open( '/tmp/target/etc/hostname', 'w' ) do | file |
  file.puts $host_name
end


File.open( '/tmp/target/etc/hosts', 'w' ) do | file |
  file.puts( <<-EOF )
127.0.0.1\tlocalhost.localdomain\tlocalhost
#{ Facter.value( 'ipaddress' ) }\t#{ $host_name }.#{ $domain_name }\t#{ $host_name }
#{ $lucie_server_ipaddress }\t#{ $lucie_server }.#{ $domain_name }\t#{ $lucie_server }

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
  EOF
end
