#!/usr/bin/env ruby


require "network_interfaces"
require "facter"


$host_name = ARGV[ 0 ]
$mac_address = ARGV[ 1 ].downcase
$ipaddress = ARGV[ 2 ]
$netmask_address = ARGV[ 3 ]
$network_address = ARGV[ 4 ]
$broadcast_address = ARGV[ 5 ]
$domain_name = ARGV[ 6 ]
$lucie_server = ARGV[ 7 ]
$lucie_server_ipaddress = ARGV[ 8 ]


NetworkInterfaces.each do | each |
  if each.name != "lo"
    File.open( "/tmp/target/etc/udev/rules.d/70-persistent-net.rules", "w" ) do | file |
      file.puts <<-RULE
SUBSYSTEM=="net", DRIVERS=="?*", ATTRS{address}=="#{ $mac_address }", NAME="#{ each.name }"
RULE
    end
    File.open( "/tmp/target/etc/network/interfaces", "w" ) do | file |
      file.puts( <<-EOF )
auto lo
iface lo inet loopback

auto #{ each.name }
iface #{ each.name } inet static
  address #{ $ipaddress }
  netmask #{ $netmask_address }
  network #{ $network_address }
  broadcast #{ $broadcast_address }
EOF
    end
  end
end


File.open( '/tmp/target/etc/hostname', 'w' ) do | file |
  file.puts $host_name
end


File.open( '/tmp/target/etc/hosts', 'w' ) do | file |
  file.puts( <<-EOF )
127.0.0.1\tlocalhost.localdomain\tlocalhost
#{ Facter.value( 'ipaddress' ) }\t#{ $host_name }.#{ $domain_name }\t#{ $host_name }
#{ $lucie_server_ipaddress }\t#{ $lucie_server }.#{ $domain_name }\t#{ $lucie_server }

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
  EOF
end
