#!/bin/sh -x

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive
chroot /tmp/target apt-get -y install ssh

mkdir -p /tmp/target/root/.ssh/
chmod 700 /tmp/target/root/.ssh/
cp /root/.ssh/authorized_keys /tmp/target/root/.ssh/
chmod 644 /tmp/target/root/.ssh/authorized_keys
ruby -pi -e "gsub( /.*ForwardAgent.*/, '    ForwardAgent yes' )" /tmp/target/etc/ssh/ssh_config
ruby -pi -e "gsub( /PermitRootLogin no/, 'PermitRootLogin yes' )" /tmp/target/etc/ssh/sshd_config
ruby -pi -e "gsub( /.*PasswordAuthentication.*/, 'PasswordAuthentication no' )" /tmp/target/etc/ssh/sshd_config
echo 'UseDNS no' >> /tmp/target/etc/ssh/sshd_config
