#!/usr/bin/env ruby


File.open( '/tmp/target/etc/default/puppet', 'w' ) do | f |
  f.puts( <<-EOF )
# Puppet doesn't like starting before it can contact the puppetmaster.
# Wait up to 30 seconds before continuing.
for n in `seq 1 30`; do
   ping -c 1 #{ ARGV[ 0 ] } >& /dev/null && break
   echo -n " $n"
   sleep 1
done
DAEMON_OPTS="-w 0 --factsync"
EOF
end


File.open( '/tmp/target/etc/puppet/puppetd.conf', 'w' ) do | f |
  f.puts( <<-EOF )
[puppetd]
logdir=/var/log/puppet
vardir=/var/lib/puppet
rundir=/var/run

server=#{ ARGV[ 0 ] }
EOF
end
