#!/usr/bin/env ruby

$apt_option = '-y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'
ENV[ 'DEBIAN_FRONTEND' ] = 'noninteractive'

system "chroot /tmp/target apt-get #{ $apt_option } install ssh"
system "cp -ar /root/.ssh /tmp/target/root/"
system %{ruby -pi -e "gsub( /PermitRootLogin no/, 'PermitRootLogin yes' )" /tmp/target/etc/ssh/sshd_config}
system %{ruby -pi -e "gsub( /.*PasswordAuthentication.*/, 'PasswordAuthentication no' )" /tmp/target/etc/ssh/sshd_config}
