#!/usr/bin/env ruby


require File.dirname(__FILE__) + '/../config/boot'
require 'command_line'
require 'lucied_blocker'
require 'lucie_daemon'
require 'optparse'


ARGV.clone.options do | opts |
  opts.on( '-l', '--lucied', 'Stop lucie daemon.' ) {
    load './script/stop_lucied'
    exit 0
  }

  opts.separator ''

  opts.on( '-h', '--help', 'Show this help message.' ) { puts opts; exit }

  opts.parse!
end


system %(sudo -p '[lucied] password for %u: ' ruby -e "load './script/stop_lucied'" )


### Local variables:
### mode: Ruby
### coding: utf-8
### indent-tabs-mode: nil
### End:
