#!/usr/bin/env ruby


require File.dirname(__FILE__) + '/../config/boot'
require 'lucied_blocker'
require 'lucie_daemon'
require 'optparse'


ARGV.clone.options do | opts |
  opts.on( '-l', '--lucied', 'Stop lucie daemon.' ) {
    unless Etc.getpwuid( Process.uid ).name == 'root'
      STDERR.puts "ERROR: You must be root."
      exit -1
    end

    begin
      unless LuciedBlocker.blocked?
        puts 'Lucie daemon (lucied) not running (no pid file).'
        exit 0
      end

      File.open( LuciedBlocker.pid_file, 'r' ) do | f |
        pid = f.read
        system "kill #{ pid }"
      end
      LuciedBlocker.release
    rescue => e
      STDERR.puts "FAILED: #{ e.message }"
      exit -1
    end

    puts "Lucie daemon (lucied) stopped."
    exit 0
  }

  opts.separator ''

  opts.on( '-h', '--help', 'Show this help message.' ) { puts opts; exit }

  opts.parse!
end
