#!/usr/bin/env ruby


ENV[ 'RAILS_ENV' ] = 'production'


require File.dirname( __FILE__ ) + '/../config/boot'
require 'optparse'


installer_name = ARGV.shift
trace = false


ARGV.options do | opts |
  opts.banner = 'usage: installer upgrade <installer-name>'

  opts.on( '-t', '--trace', 'Print out exception stack traces' ) do
    trace = true
  end
  opts.on( '-h', '--help', 'Show this help message.' ) do
    puts opts
    exit 1
  end

  args = opts.parse!

  unless installer_name
    STDERR.puts 'Installer name is mandatory'
    STDERR.puts
    puts opts
    exit -1
  end

  # Installer Name can only contain alphanumeric characters
  if installer_name.match /[^-_a-zA-Z0-9]/
    STDERR.puts "'#{ installer_name }' is not a valid installer name. Installer name should only contain alphanumeric characters, dashes and underscores, and no whitespace."
    exit -1
  end
end


puts "Upgrading installer '#{ installer_name }' (this may take a while)..."

begin
  require RAILS_ROOT + '/config/environment'

  installer = Installers.find( installer_name )
  unless installer
    raise "Installer '#{ installer_name }' not found."
  end
  installer.upgrade
rescue => e
  if trace
    raise
  else
    STDERR.puts "FAILED: #{ e.message }"
    exit -1
  end
end


### Local variables:
### mode: Ruby
### coding: utf-8
### indent-tabs-mode: nil
### End:
